version: "3.8"
services:
  db:
    image: postgis/postgis:15-3.4
    container_name: gerkon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sqlbase7comiloveu
      POSTGRES_DB: gerkon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./herkon_init.sql:/docker-entrypoint-initdb.d/herkon_init.sql
volumes:
  pgdata:
